stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - club_server_133
  only:
    - develop
  before_script:
    - cd /opt/jeanswest-club/jeanwest-admin/
  script:
    - sudo git pull origin
    - sudo git checkout develop
    - sudo yarn build
    - sudo pm2 restart jeanswest-admin
  environment:
    name: club_server
