image: ubuntu

before_script:
# - echo "nameserver 8.8.8.8" | tee /etc/resolv.conf > /dev/null
#  - apt-get update -yqq
#  - apt-get install sudo -yqq
#  - apt-get install sudo -f
# - apt-get install git -yqq
  - apt-get update -qq
  - apt-get install sudo -qq
  - apt-get install git -qq

 
 
# Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$DEV_SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

Develop_Stage:
  type: deploy
  environment:
    name: develop
  script:

    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "pm2 ls"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "pm2 delete jeanswest-admin > /dev/null 2>&1 || FAILED=true"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "rm -rf * /home/gitlab/jeanswest-admin/"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "cd /home/gitlab/ && git clone git@gitlab.avakatan.ir:K.Karami/jeanwesr-admin.git jeanswest-admin"
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "cd /home/gitlab/jeanswest-admin/ && yarn" 
    - ssh -tt gitlab@JWApp-Dev-0-1.AVAKATAN.ir "cd /home/gitlab/jeanswest-admin/ && pm2 start 'yarn serve' -p 8080 --name jeanswest-admin"
    - echo "http://10.0.1.111:8080/"

  only:
    - develop
