stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - club_server_133
  only:
    - develop
  before_script:
    - cd /opt/jeanswest-club/jeanwest-admin/
  script:
    - sudo git pull origin
    - sudo git checkout develop
    - sudo yarn
    - sudo pm2 restart jeanswest-admin
    - echo "Please check 10.0.1.133:3000 or https://admin.jeanswest.club"
  environment:
    name: club_server