stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - club_dev
  only:
    - develop
  before_script:
    - cd /opt/jeanswest-club/jeanwest-admin/
  script:
    - sudo git pull origin
    - sudo git checkout develop
    - sudo yarn
    - sudo pm2 restart jeanswest-admin
    - echo "Please check 10.0.1.89:3000"
  environment:
    name: develop
  # test